server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javitar02/configServer.git
        default-label: main
        search-paths:
        - 'service'
